apiVersion: v1
kind: ConfigMap
metadata:
  name:  {{ include "konga.fullname" . }}-snapshot
  labels:
    app.kubernetes.io/name: {{ include "konga.name" . }}
    helm.sh/chart: {{ include "konga.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  kong_node.data: |
    module.exports = [
        {
            "name": "Kong",
            "type": "default",
            "kong_admin_url": "http://{{ .Values.kong.service }}:{{ .Values.kong.admin_port }}",
            "health_checks": false,
            "active" : true,
        }
    ]
  snapshot.json: |
    {
        "createdUser": null,
        "updatedUser": null,
        "id": 2,
        "name": "November2021",
        "kong_node_name": "Kong",
        "kong_node_url": "http://kong:8001",
        "kong_version": "0-10-x",
        "data": {
            "services": [
                {
                    "write_timeout": 60000,
                    "path": null,
                    "name": "status",
                    "host": "localhost",
                    "tls_verify_depth": null,
                    "retries": 5,
                    "port": 8000,
                    "connect_timeout": 60000,
                    "read_timeout": 60000,
                    "created_at": 1623859719,
                    "updated_at": 1624975444,
                    "id": "90a37cb9-2c01-472b-8fff-715835e56156",
                    "protocol": "http",
                    "tls_verify": null,
                    "client_certificate": null,
                    "tags": [],
                    "ca_certificates": null,
                    "extras": {}
                },
                {
                    "write_timeout": 60000,
                    "path": null,
                    "name": "Forno",
                    "host": "rc1-fullnodes-rpc.rc1",
                    "tls_verify_depth": null,
                    "retries": 5,
                    "port": 8545,
                    "connect_timeout": 60000,
                    "read_timeout": 60000,
                    "created_at": 1623232145,
                    "updated_at": 1624975444,
                    "id": "d98c9e59-dc44-4bad-81ca-d399724462b0",
                    "protocol": "http",
                    "tls_verify": null,
                    "client_certificate": null,
                    "tags": [],
                    "ca_certificates": null,
                    "extras": {}
                }
            ],
            "routes": [
                {
                    "https_redirect_status_code": 426,
                    "service": {
                        "id": "90a37cb9-2c01-472b-8fff-715835e56156"
                    },
                    "name": "health-check",
                    "request_buffering": true,
                    "response_buffering": true,
                    "path_handling": "v0",
                    "paths": [
                        "/status",
                        "/status*",
                        "/kong/status",
                        "/kong/status*"
                    ],
                    "methods": [
                        "GET"
                    ],
                    "preserve_host": false,
                    "destinations": null,
                    "strip_path": true,
                    "headers": null,
                    "created_at": 1623859737,
                    "hosts": null,
                    "id": "37f4e0db-fbc9-4aa3-9f47-5c957c54efdc",
                    "protocols": [
                        "http",
                        "https"
                    ],
                    "regex_priority": 100,
                    "updated_at": 1624975444,
                    "snis": null,
                    "sources": null,
                    "tags": null
                },
                {
                    "https_redirect_status_code": 426,
                    "service": {
                        "id": "d98c9e59-dc44-4bad-81ca-d399724462b0"
                    },
                    "name": "forno",
                    "request_buffering": true,
                    "response_buffering": true,
                    "path_handling": "v0",
                    "paths": [
                        "/",
                        "/*"
                    ],
                    "methods": null,
                    "preserve_host": false,
                    "destinations": null,
                    "strip_path": true,
                    "headers": null,
                    "created_at": 1623232306,
                    "hosts": null,
                    "id": "eaa4fa2b-cd10-4c61-a2ac-6831adcd0752",
                    "protocols": [
                        "http",
                        "https"
                    ],
                    "regex_priority": 10,
                    "updated_at": 1635763609,
                    "snis": null,
                    "sources": null,
                    "tags": null
                }
            ],
            "consumers": [
                {
                    "username": "anonymous",
                    "custom_id": null,
                    "created_at": 1623404756,
                    "tags": [],
                    "id": "1532538d-cb47-48fa-8a8e-b21952644a6e",
                    "credentials": {
                        "key-auths": []
                    }
                },
                {
                    "username": "komenci",
                    "custom_id": null,
                    "created_at": 1623404316,
                    "tags": [],
                    "id": "bdfbe991-2e69-4d50-bf79-4681be7f5949",
                    "credentials": {
                        "key-auths": [
                            {
                                "ttl": null,
                                "key": "komenci",
                                "consumer": {
                                    "id": "bdfbe991-2e69-4d50-bf79-4681be7f5949"
                                },
                                "created_at": 1636497268,
                                "tags": null,
                                "id": "ef552784-95ad-41e2-b70c-8b188eaad87e"
                            }
                        ]
                    }
                }
            ],
            "plugins": [
                {
                    "service": {
                        "id": "d98c9e59-dc44-4bad-81ca-d399724462b0"
                    },
                    "name": "rate-limiting",
                    "consumer": {
                        "id": "bdfbe991-2e69-4d50-bf79-4681be7f5949"
                    },
                    "config": {
                        "path": null,
                        "hide_client_headers": false,
                        "second": 10000000,
                        "minute": 1000000000,
                        "hour": null,
                        "day": null,
                        "month": null,
                        "year": null,
                        "header_name": "CF-Connecting-IP",
                        "redis_timeout": 2000,
                        "redis_database": 0,
                        "redis_host": null,
                        "redis_port": 6379,
                        "limit_by": "header",
                        "redis_password": null,
                        "policy": "cluster",
                        "fault_tolerant": true
                    },
                    "id": "175852a3-9891-4b26-b0f3-f2832bceadbf",
                    "enabled": true,
                    "created_at": 1624889602,
                    "route": null,
                    "tags": null,
                    "protocols": [
                        "grpc",
                        "grpcs",
                        "http",
                        "https"
                    ]
                },
                {
                    "service": {
                        "id": "90a37cb9-2c01-472b-8fff-715835e56156"
                    },
                    "name": "request-termination",
                    "consumer": null,
                    "config": {
                        "status_code": 200,
                        "message": "ok",
                        "content_type": null,
                        "body": null
                    },
                    "id": "18ccb4e4-b09c-4251-af1d-d3367f7ca667",
                    "enabled": true,
                    "created_at": 1623859751,
                    "route": null,
                    "tags": null,
                    "protocols": [
                        "grpc",
                        "grpcs",
                        "http",
                        "https"
                    ]
                },
                {
                    "service": null,
                    "name": "file-log",
                    "consumer": {
                        "id": "1532538d-cb47-48fa-8a8e-b21952644a6e"
                    },
                    "config": {
                        "custom_fields_by_lua": null,
                        "path": "/tmp/kong2323.log",
                        "reopen": false
                    },
                    "id": "53493e2a-2622-4d6b-ad03-94f6520dde5c",
                    "enabled": false,
                    "created_at": 1636644993,
                    "route": null,
                    "tags": null,
                    "protocols": [
                        "grpc",
                        "grpcs",
                        "http",
                        "https"
                    ]
                },
                {
                    "service": {
                        "id": "d98c9e59-dc44-4bad-81ca-d399724462b0"
                    },
                    "name": "rate-limiting",
                    "consumer": {
                        "id": "1532538d-cb47-48fa-8a8e-b21952644a6e"
                    },
                    "config": {
                        "path": null,
                        "hide_client_headers": false,
                        "second": null,
                        "minute": 50000,
                        "hour": 2500000,
                        "day": null,
                        "month": null,
                        "year": null,
                        "header_name": "CF-Connecting-IP",
                        "redis_timeout": 2000,
                        "redis_database": 0,
                        "redis_host": null,
                        "redis_port": 6379,
                        "limit_by": "header",
                        "redis_password": null,
                        "policy": "cluster",
                        "fault_tolerant": true
                    },
                    "id": "6060fd61-cf04-4bb2-a426-0aea585ac159",
                    "enabled": true,
                    "created_at": 1624889534,
                    "route": null,
                    "tags": null,
                    "protocols": [
                        "grpc",
                        "grpcs",
                        "http",
                        "https"
                    ]
                },
                {
                    "service": null,
                    "name": "ip-restriction",
                    "consumer": {
                        "id": "1532538d-cb47-48fa-8a8e-b21952644a6e"
                    },
                    "config": {
                        "deny": [
                            "120.221.100.45/32",
                            "120.221.13.76/32",
                            "223.99.251.89/32",
                            "49.69.236.68/32",
                            "120.221.13.148/32",
                            "120.221.13.0/24",
                            "186.189.238.210/32"
                        ],
                        "allow": null
                    },
                    "id": "900048e1-fd11-46dd-9ec9-ab9172919250",
                    "enabled": true,
                    "created_at": 1636064489,
                    "route": null,
                    "tags": null,
                    "protocols": [
                        "grpc",
                        "grpcs",
                        "http",
                        "https"
                    ]
                },
                {
                    "service": {
                        "id": "d98c9e59-dc44-4bad-81ca-d399724462b0"
                    },
                    "name": "key-auth",
                    "consumer": null,
                    "config": {
                        "key_names": [
                            "apikey"
                        ],
                        "run_on_preflight": true,
                        "key_in_header": true,
                        "key_in_query": true,
                        "key_in_body": false,
                        "anonymous": "1532538d-cb47-48fa-8a8e-b21952644a6e",
                        "hide_credentials": false
                    },
                    "id": "96259f8e-0484-4c98-9f4d-d4406c354407",
                    "enabled": true,
                    "created_at": 1624889633,
                    "route": null,
                    "tags": null,
                    "protocols": [
                        "grpc",
                        "grpcs",
                        "http",
                        "https"
                    ]
                },
                {
                    "service": null,
                    "name": "prometheus",
                    "consumer": null,
                    "config": {
                        "per_consumer": true
                    },
                    "id": "c3e6ca20-d3e4-4605-b901-5302bb447359",
                    "enabled": true,
                    "created_at": 1626079016,
                    "route": null,
                    "tags": null,
                    "protocols": [
                        "grpc",
                        "grpcs",
                        "http",
                        "https"
                    ]
                }
            ],
            "acls": [
                {
                    "group": "noratelimit",
                    "consumer": {
                        "id": "bdfbe991-2e69-4d50-bf79-4681be7f5949"
                    },
                    "created_at": 1623404350,
                    "tags": null,
                    "id": "57187a97-d48b-4128-b007-281c0ed33659"
                }
            ],
            "upstreams": [],
            "certificates": [],
            "snis": []
        },
        "createdAt": "2021-11-19T11:56:45.000Z",
        "updatedAt": "2021-11-19T11:56:45.000Z"
    }
