blockscout:
  indexer:
    db:
      connectionName: celo-testnet-production:us-west1:rc1staging
      proxy:
        resources:
          requests:
            memory: 4Gi
            cpu: 500m
    poolSize: 100
    resources:
      requests:
        memory: 12Gi
        cpu: 5
  api:
    autoscaling:
      maxReplicas: 2
      minReplicas: 1
      target:
        cpu: 70
    db:
      connectionName: celo-testnet-production:us-west1:rc1staging-replica
      proxy:
        resources:
          requests:
            memory: 500Mi
            cpu: 300m
    poolSize: 30
    resources:
      requests:
        memory: 500Mi
        cpu: 500m
  web:
    host: rc1staging-blockscout.celo-testnet.org
    autoscaling:
      maxReplicas: 2
      minReplicas: 1
      target:
        cpu: 70
    db:
      connectionName: celo-testnet-production:us-west1:rc1staging
      proxy:
        resources:
          requests:
            memory: 500Mi
            cpu: 300m
    poolSize: 30
    resources:
      requests:
        memory: 250M
        cpu: 500m
    recaptchaSecretName: rc1staging-blockscout-recaptcha
    stats:
      enabled: true
      reportUrl: https://datastudio.google.com/embed/reporting/e0a253b1-fa37-43d0-bbc3-2706a64f2211/page/hDehC?hl=en
  metadataCrawler:
    enabled: true
  archiveNodes:
    jsonrpcHttpUrl: http://rc1staging-archivenodes-rpc:8545
    jsonrpcWsUrl: ws://rc1staging-archivenodes-rpc:8545
  metrics:
    enabled: true
  secrets:
    segmentKey: gcp:secretmanager:projects/365081401101/secrets/rc1staging-blockscout-segmentKey
  chain:
    subnetwork: Celo
    networkID: 42220
